# LA for ML #6

In [4]:
# call array from numpy library
from numpy import array

# define 2 vectors a and b each has 1 row and 3 columns
a = array([1, 2, 3])
b = array([1, 2, 3])

# adding 2 vectors
c = a + b
print(c)

# subtracting 2 vectors
c = a - b
print(c)

# multipling 2 vectors
c = a * b
print(c)

# divide a vector by another one
c = a / b
print(c)

# please notice that these vectors have the same dimensions

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]


In [5]:
# call array from numpy
from numpy import array

# define 2 vectors a and b
a = array([1,2,3])
b = array([1,2,3])

# find the dot product of a and b (C = 1*1+2*2+3*3), display the output
C = a.dot(b)
print(C)

14


In [6]:
# call array from numpy
from numpy import array

# define vector a with 1 row and 3 columns
a = array([1,2,3])

# define scalar s
s = 0.5

# multiply scalar s by vector a, display the output
C = s*a
print(C)

[0.5 1.  1.5]


In [7]:
# call positive infinity value from mathematics library
from math import inf

# call array from numpy
from numpy import array

# call norm function (used to find the length of the the vector) from linear algebra library
from numpy.linalg import norm

# define vector a with 1 row and 3 columns
a = array([1,2,3])

# find vector's length using absolute function
# l1 = |1|+|2|+|3|
l1=norm(a,1)

# find vector's length using square function
# l2 = sqr (1**2 + 2**2 + 3**2)
l2=norm(a,2)

# find the vector's length by comparing the elements
# maxnorm = max (|1|, |2|, |3|)
maxnorm=norm(a,inf)

# display vector's length results
print(l1,l2,maxnorm)

6.0 3.7416573867739413 3.0
