# LA for ML #5

In [5]:
a = [1, 2, 3]
b = [1, 2, 3]
c = a + b

In [6]:
c

[1, 2, 3, 1, 2, 3]

In [7]:
# broadcast scalar to one-dimensional array(vector)
from numpy import array

# define vector a with three elements
a = array([1, 2, 3])
print(a)

# define scalar b
b = 2

# display b value
print(b)

# broadcast b scalar through vector a and save it in c
c = a + b

# display the result of broadcasting
print(c)

[1 2 3]
2
[3 4 5]


In [8]:
# broadcast vector to two-dimensional array
from numpy import array

# define array A with 2 rows and 3 columns
A = array([[1, 2, 3], [4, 5, 6]])
# display A elements
print(A)

# define vector B that has 1 row and 3 columns
B = array([7,8,9])
# display B elements
print(B)

# broadcast B array through A 
C = A + B
# display the output
print(C)

[[1 2 3]
 [4 5 6]]
[7 8 9]
[[ 8 10 12]
 [11 13 15]]


In [9]:
# call array from numpy
from numpy import array

# define array A with 2 rows and 3 columns
A = array([[1, 2, 3],[5,6,7]])

# define scalar B with 1 row and 2 columns
B = array([7,8])

# broadcast B 
C = A + B

#display the output
print(C)

# This code produces an error since the number of B columns are not equal to A columns

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 