# LA for ML #3

In [1]:
# calling array function from numpy
from numpy import array

# defining array with three elements
a = array([1,2,3])

# printing what's a contains
print(a)

# to know how many rows and columns in a
print(a.shape)

# to know the datatype of a's elements
print(a.dtype)

[1 2 3]
(3,)
int64


In [7]:
# calling empty function from numpy
from numpy import empty

# create an array that has 3 rows and columns
# the numbers will be assigned randomly
# everytime that your run this you will get different result
a = empty([3,3])

#print a's elements
print(a)

[[6.92832276e-310 4.65611972e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [8.36329978e-299 1.09921079e-311 3.95252517e-322]]


In [9]:
# calling zeros function from numpy
from numpy import zeros

# create an array with one row and three columns 
# all its elements are zeros
a = zeros([3])

# printing a's elements
print(a)

[0. 0. 0.]


In [11]:
# calling ones function from numpy
from numpy import ones

# create an array with five rows and one column
# all its elements are ones
a = ones([5,1])

# printing a's elements
print(a)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [14]:
# calling array and vertical stack functions from numpy
from numpy import array
from numpy import vstack

# creating a1 array with three elements
a1 = array([1,2,3])
print(a1)

# creating a2 array with different three elements than a1
a2 = array([4,5,6])
print(a2)

# create new array a3 that has a1 as the first row and a2 as the second
a3 = vstack((a1,a2))
print(a3)

# printing a3 rows and columns
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [15]:
# calling array and horizontal stack functions from numpy
from numpy import array
from numpy import hstack

# creating a1 array with three elements
a1 = array([1,2,3])
print(a1)

# creating a2 array with different three elements than a1
a2 = array([4,5,6])
print(a2)

# create new array a3 cotains a1 elements with a2 attached to the right side
a3 = hstack((a1,a2))
print(a3)

# printing a3 rows and columns
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)
